## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: "\u2049 FAQ"
    url: "https://necord.org/faq"
    about: "Make sure you have read the Frequently Asked Questions page."
  - name: "\u2753 Discord Community of Necord"
    url: "https://discord.gg/mcBYvMTnwP"
    about: "Please ask support questions or discuss suggestions/enhancements here."
